-- DEPRECATED — do not use this file to bootstrap a local PostgreSQL database.
--
-- This script previously defined `kb_entries.kb_id` as a UUID with a
-- uuid_generate_v4() default. The application generates its own TEXT primary
-- keys (e.g. "kb_abc123def456") and references them from `kb_embeddings`, so a
-- UUID column produces foreign-key type-mismatch errors and a broken KB.
--
-- The canonical, correct local-Postgres bootstrap is:
--
--     scripts/ci_bootstrap_schema.sql
--
-- It uses the TEXT primary key the app expects, includes the attribution
-- columns required by lore.search (author, source_type, verified, trust_score),
-- and matches what LocalPostgresClient._init_schema expects on first connect
-- (the rest — kb_embeddings, retrieval_telemetry, hard_negative_pairs — is
-- auto-created at runtime).
--
-- To bootstrap a local Postgres + pgvector database, run:
--
--     psql -h localhost -U lore_user -d lore -f scripts/ci_bootstrap_schema.sql
--
-- This file is retained only as a redirect so existing onboarding links don't
-- 404; it intentionally creates no objects.
